before_script:
  - cd frontend; npm install; cd ..
script:
  - bundle exec rspec
  - cd frontend; npm test; cd ..
after_script:
  - cd frontend; ./node_modules/.bin/codeclimate < coverage/lcov.info; cd ..
addons:
  code_climate:
    repo_token: 8500297832857131cc64d8d8deb990c28120919675eca4f18fa3663ff6583f6f
